services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\AiImageMeta\:
    resource: '../Classes/*'

  WapplerSystems\AiImageMeta\EventListener\BeforeFormEnginePageInitialized:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent
